In [1]:
import numpy as np
n = int(input())
diagonal = np.arange(1, n+1)
print(np.diag(diagonal))

5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
import numpy as np
n=int(input())
ar = np.ones((n,n), dtype=int)
ar[1::2]=0
print(ar)

5
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [6]:
import numpy as np
n=int(input())
print(np.arange(n, -1, -1))

5
[5 4 3 2 1 0]


In [10]:
import numpy as np
n, m = (int(i) for i in input().split(" "))
array = np.random.random((n, m))
print(array)
print("мінімум: {}".format(round(np.amin(array), 3)))
print("максимум: {}".format(round(np.amax(array), 3)))
print("середнє: {}".format(round(np.mean(array), 3)))
print("дисперсія: {}".format(round(np.std(array), 3)))

5 6
[[0.70333284 0.53009954 0.28462693 0.7756117  0.62156128 0.34414323]
 [0.70729616 0.51289215 0.98958062 0.79559331 0.46931753 0.41916432]
 [0.54017305 0.0925591  0.86328277 0.13554504 0.2024658  0.22889051]
 [0.56541724 0.63920855 0.37159003 0.98716783 0.84294559 0.57878448]
 [0.67868076 0.91689839 0.861273   0.57820817 0.79715819 0.81191992]]
мінімум: 0.093
максимум: 0.99
середнє: 0.595
дисперсія: 0.247


In [40]:
import numpy as np
n=int(input())
ar = np.ones((n,n), dtype=int)
ar[0::n-1]=0
ar[::, 0::n-1]=0
print(ar)

8
[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]


In [44]:
import numpy as np
ar3 = np.tile([[0, 1], [1, 0]], (4,4))
print(ar3)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [46]:
import numpy as np
n=int(input())
ar = np.ones((n,n), dtype=int)
ar[::, 0::2]=0
print(ar)

6
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]]


In [53]:
import numpy as np
n = int(input())
array = [round(i, 3) for i in np.random.random(n)]
print("Початковий вектор: {}".format(array))
print("Змінений вектор: {}".format(np.where(array==np.amax(array), 0, array)))

7
Початковий вектор: [0.41, 0.906, 0.91, 0.979, 0.713, 0.212, 0.575]
Змінений вектор: [0.41  0.906 0.91  0.    0.713 0.212 0.575]


In [2]:
import numpy as np
n, m = [int(i) for i in input().split(" ")]
array = np.random.randint(0, m, (n, n))
print("Початковий масив")
print(array)
print("Змінений масив")
print(np.where(array == np.amax(array), -array,array))

5 10
Початковий масив
[[4 0 5 6 9]
 [2 9 6 4 1]
 [0 7 0 6 2]
 [4 2 3 1 7]
 [5 6 7 6 3]]
Змінений масив
[[ 4  0  5  6 -9]
 [ 2 -9  6  4  1]
 [ 0  7  0  6  2]
 [ 4  2  3  1  7]
 [ 5  6  7  6  3]]


In [78]:
import numpy as np
system = np.array([[2, -1, 1, -1, 1],[2, -1, 0, -3, 2],[3, 0, -1, 1, -3],[2, 2, -2, 5, -6]])
a1, a2, a3, a4, b= np.hsplit(system, [1,2,3,4])

delta = np.concatenate([a1, a2, a3, a4], axis = 1)
delta1 = np.concatenate([b, a2, a3, a4], axis = 1)
delta2 = np.concatenate([a1, b, a3, a4], axis = 1)
delta3 = np.concatenate([a1, a2, b, a4], axis = 1)
delta4 = np.concatenate([a1, a2, a3, b], axis = 1)
print(system)
print(delta)
print(delta1)
print(delta2)
print(delta3)
print(delta4)

x1 = np.linalg.det(delta1) / np.linalg.det(delta)
x2 = np.linalg.det(delta2) / np.linalg.det(delta)
x3 = np.linalg.det(delta3) / np.linalg.det(delta)
x4 = np.linalg.det(delta4) / np.linalg.det(delta)

print("x1 = {}\nx2 = {}\nx3 = {}\nx4 = {}\n".format(x1, x2, x3, x4))
print("Перевірка за допомогою матричного множення: ")
print(system[::, :4:].dot([x1, x2, x3, x4]))

print("Перевірка за допомогою функції numpy.lanalg.solve(): ")
print(np.linalg.solve(system[::, :4:], system[::, 4]))
print(system[::, :4:].dot(np.linalg.solve(system[::, :4:], system[::, 4])))

[[ 2 -1  1 -1  1]
 [ 2 -1  0 -3  2]
 [ 3  0 -1  1 -3]
 [ 2  2 -2  5 -6]]
[[ 2 -1  1 -1]
 [ 2 -1  0 -3]
 [ 3  0 -1  1]
 [ 2  2 -2  5]]
[[ 1 -1  1 -1]
 [ 2 -1  0 -3]
 [-3  0 -1  1]
 [-6  2 -2  5]]
[[ 2  1  1 -1]
 [ 2  2  0 -3]
 [ 3 -3 -1  1]
 [ 2 -6 -2  5]]
[[ 2 -1  1 -1]
 [ 2 -1  2 -3]
 [ 3  0 -3  1]
 [ 2  2 -6  5]]
[[ 2 -1  1  1]
 [ 2 -1  0  2]
 [ 3  0 -1 -3]
 [ 2  2 -2 -6]]
x1 = -1.4802973661668788e-16
x2 = 2.0
x3 = 1.666666666666667
x4 = -1.333333333333333

Перевірка за допомогою матричного множення: 
[ 1.  2. -3. -6.]
Перевірка за допомогою функції numpy.lanalg.solve(): 
[ 7.40148683e-17  2.00000000e+00  1.66666667e+00 -1.33333333e+00]
[ 1.  2. -3. -6.]


In [64]:
import numpy as np
A = np.array([[1,0,3], [-2,0,1], [-1,3,1]])
B = np.array([[7,5,2], [0,1,2], [-3,-1,-1]])

print(A)
print()
print(B)
print()
print("(2A-B)(3A+B)-2AB\n")

print("\n2A-B\n")
print(2*A, end="\n - \n")
print(B, end = "\n = \n")
print(2*A - B)

print("\n3A+B\n")
print(3*A, end="\n + \n")
print(B, end = "\n = \n")
print(3*A + B)

print("\n(2A-B)(3A+B)\n")
print(2*A - B, end="\n*\n")
print(3*A + B, end="\n=\n")
print((2*A - B).dot((3*A + B)))

print("\n(2A-B)(3A+B)-2AB\n")
print((2*A - B)*(3*A + B), end = "\n-\n")
print(2*A*B, end = "\n=\n")
print((2*A - B).dot((3*A + B)) - 2*A.dot(B))

[[ 1  0  3]
 [-2  0  1]
 [-1  3  1]]

[[ 7  5  2]
 [ 0  1  2]
 [-3 -1 -1]]

(2A-B)(3A+B)-2AB


2A-B

[[ 2  0  6]
 [-4  0  2]
 [-2  6  2]]
 - 
[[ 7  5  2]
 [ 0  1  2]
 [-3 -1 -1]]
 = 
[[-5 -5  4]
 [-4 -1  0]
 [ 1  7  3]]

3A+B

[[ 3  0  9]
 [-6  0  3]
 [-3  9  3]]
 + 
[[ 7  5  2]
 [ 0  1  2]
 [-3 -1 -1]]
 = 
[[10  5 11]
 [-6  1  5]
 [-6  8  2]]

(2A-B)(3A+B)

[[-5 -5  4]
 [-4 -1  0]
 [ 1  7  3]]
*
[[10  5 11]
 [-6  1  5]
 [-6  8  2]]
=
[[-44   2 -72]
 [-34 -21 -49]
 [-50  36  52]]

(2A-B)(3A+B)-2AB

[[-50 -25  44]
 [ 24  -1   0]
 [ -6  56   6]]
-
[[14  0 12]
 [ 0  0  4]
 [ 6 -6 -2]]
=
[[-40  -2 -70]
 [  0   1 -39]
 [-30  42  46]]


In [77]:
import numpy as np
A = np.array([[5,-1, 3],[0,2,-1],[-2,-1,0]])
B = np.array([[3,7,-2],[1,1,-2],[0,1,3]])

print("Матриця А")
print(A)
print("Матриця В")
print(B)
print("Рішення:")
print("inv(A) * B = ")
result = B.dot(np.linalg.inv(A))
print(result)
print("Перевірка за допомогою матричного множення: ")
print(result.dot(A))
print("Перевірка за допомогою функції numpy.linalg.solve(): ")
print(np.linalg.solve(result, B))

Матриця А
[[ 5 -1  3]
 [ 0  2 -1]
 [-2 -1  0]]
Матриця В
[[ 3  7 -2]
 [ 1  1 -2]
 [ 0  1  3]]
Рішення:
inv(A) * B = 
[[ 6.0000000e-01  3.8000000e+00 -8.8817842e-16]
 [-1.4000000e+00 -2.2000000e+00 -4.0000000e+00]
 [ 2.8000000e+00  5.4000000e+00  7.0000000e+00]]
Перевірка за допомогою матричного множення: 
[[ 3.00000000e+00  7.00000000e+00 -2.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -2.00000000e+00]
 [ 1.77635684e-15  1.00000000e+00  3.00000000e+00]]
Перевірка за допомогою функції numpy.linalg.solve(): 
[[ 5.00000000e+00 -1.00000000e+00  3.00000000e+00]
 [-5.04101265e-16  2.00000000e+00 -1.00000000e+00]
 [-2.00000000e+00 -1.00000000e+00  1.54043445e-15]]
